spring.application.name=Smartify
spring.datasource.url=jdbc:postgresql://192.168.178.42:5432/temperatureAndMotionDetectorDB
spring.datasource.username=deadeye
spring.datasource.password=deadeye
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.show_sql=false
